source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'PowerTodo' do
    pod 'Alamofire', '~> 4.0'
    pod 'NVActivityIndicatorView'
    pod 'SwipyCell', '~> 2.0.0'
end
